### ISSUE TITLE
[Meta] Core interfaces implementation

### ISSUE THREAD

**Issue by sufyankhanrao** [apimatic/core-interfaces-java#1]
This is a parent ticket to track all implementation tasks. The task breakdown is as follows;-

- [x] #2
- [x] Vet interface names and related documentation in those interfaces
- [x] Update ReadMe when interfaces get stable.
- [x] #3
- [x] Add CD workflow for package publishing

**Comment by sufyankhanrao** [comment]
Since all tasks have been addressed so closing this tracker issue.
